# Generated by Django 3.0.6 on 2020-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_species',
            fields=[
                ('id', models.SmallIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('species', models.CharField(blank=True, max_length=5, null=True, verbose_name='種族')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
