# Generated by Django 3.0.6 on 2020-06-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_test_app', '0002_auto_20200625_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecies',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('species', models.CharField(blank=True, max_length=5, null=True, verbose_name='種族')),
            ],
        ),
        migrations.DeleteModel(
            name='user_species',
        ),
    ]
