# Generated by Django 3.0.6 on 2020-06-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_test_app', '0003_auto_20200625_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='species',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='login_test_app.UserSpecies', verbose_name='種族'),
            preserve_default=False,
        ),
    ]
